=== irmscher2000/Lenguajes-de-marcas-y-sistemas-en-gesti-n-de-la-informacion/LMSGI_04/parque.dtd
<!ELEMENT parque (materiales, camiones, bomberos)>

<!ELEMENT materiales (material+)>
<!ELEMENT material (nombre, tipo, unidades)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

<!ELEMENT camiones (camion+)>
<!ELEMENT camion (matricula, longitudVehiculo, longitudEscalera, capacidadExtintor)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT longitudVehiculo (#PCDATA)>
<!ELEMENT longitudEscalera (#PCDATA)>
<!ELEMENT capacidadExtintor (#PCDATA)>      

<!ELEMENT bomberos (bombero+)>
<!ELEMENT bombero (dni, rango, nombreApellidos, direccion, edad, telefonos?)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT rango (#PCDATA)>
<!ELEMENT nombreApellidos (#PCDATA)>
<!ELEMENT direccion (calle, cp, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT telefonos (telefono+)>
<!ELEMENT telefono (#PCDATA)>

<!ATTLIST material tipo (extincion | ayuda_accidentes | otras_actuaciones) #REQUIRED>
<!ATTLIST camion capacidadExtintor (agua | espuma) #REQUIRED>
<!ATTLIST bombero rango  (srgt | cabo | bomb| bombc | cond) #REQUIRED>
<!ATTLIST parque ubicacion CDATA #IMPLIED>
<!ATTLIST parque
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== irmscher2000/Lenguajes-de-marcas-y-sistemas-en-gesti-n-de-la-informacion/LMSGI_04/ARCHIVO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Eugen Moga
    LMSGI04_Tarea
-->
<!DOCTYPE parque SYSTEM "parque.dtd">

<parque>
    <materiales>
        <material tipo="extincion">
            <nombre>Manguera</nombre>
            <tipo>extincion</tipo>
            <unidades>50</unidades>
        </material>
        <material tipo="otras_actuaciones">
            <nombre>Extintor</nombre>
            <tipo>otras_actuaciones</tipo>
            <unidades>50</unidades>
        </material>
    </materiales>
    <camiones>
        <camion capacidadExtintor="agua">
            <matricula>123 BCD</matricula>
            <longitudVehiculo>13</longitudVehiculo>
            <longitudEscalera>20</longitudEscalera>
            <capacidadExtintor>200</capacidadExtintor>
        </camion>
    </camiones>
    <bomberos>
        <bombero rango="srgt">
            <dni>12345678A</dni>
            <rango>srgt</rango>
            <nombreApellidos>Eugen Moga</nombreApellidos>
            <direccion>
                <calle>Calle Mallor </calle>
                <cp>31530</cp>
                <provincia>Navarra</provincia>
            </direccion>
            <edad>34</edad>
            <telefonos>
                <telefono>601234567</telefono>
                <telefono>948234567</telefono>
                <telefono>948034567</telefono>
            </telefonos>
        </bombero>
    </bomberos>
</parque>
